name: Java CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'gradle.properties'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Get file name
      run: echo "file_path=$(find build/libs | grep '[0-9].jar')" >> $GITHUB_OUTPUT
      id: var

    - name: Upload to CurseForge
      uses: itsmeow/curseforge-upload@v3
      with:
        token: ${{ secrets.CURSEFORGE_TOKEN }}
        project_id: 386188
        game_endpoint: minecraft
        file_path: ${{ steps.var.outputs.file_path }}
        changelog: See recent commits [here](https://github.com/eutro/MultiblockTweaker/commits/${{ github.sha }}). This is only marked as a beta release so CurseForge shows it on the front page.
        changelog_type: markdown
        # 1.12.2, Java 8
        game_versions: 6756,4458
        release_type: beta
        relations: jei:optionalDependency,crafttweaker:requiredDependency,gregtech-ce-unofficial:requiredDependency
